### PR TITLE
remove the joint limits from the 48 DOFs human models

### PR DESCRIPTION
**Pull request by kouroshD**
The objective of this PR is t enlarge the joint range of motion, i.e., by relaxing the joint limits.
Related issue https://github.com/robotology/human-gazebo/issues/21

### CODE REVIEW

**Comment by kouroshD** [comment]
@lrapetti  @Yeshasvitvs  please when you have some time review the PR. I could not add you as reviewers.

**Comment by lrapetti** [comment]
Thanks, @kouroshD. I wouldn't remove completely the models with the joint limits though, since in some cases they behave better, preventing some unnatural motions) What about keeping both the 48DoFs model with and without limits?

**Comment by kouroshD** [comment]
> Thanks, @kouroshD. I wouldn't remove completely the models with the joint limits though, since in some cases they behave better, preventing some unnatural motions) What about keeping both the 48DoFs model with and without limits?

@lrapetti  it is done. Let me know if it is fine. Thanks.

**Review by lrapetti — APPROVED** [review]
Looks good, thanks @kouroshD

**Pull request merged**
